Feature/us3bis
WildCodeSchool/valiris-api pull request #9
Opened 2020-06-23 09:10 UTC by nathanguillaumin

Salut @ComicScrip,
Nous avons ajouté des requêtes pour la traduction et changé le nom de certaines clés sur les routes + ajout nodemailer. Peux-tu valider la PR stp?
Merci d'avance !

2020-06-23 11:48 UTC, ComicScrip requested changes

2020-06-23 11:48 UTC, ComicScrip commented on migrations/sqls/20200601164349-initDB-up.sql
> +  `name` varchar(255) DEFAULT NULL,
Attention, ne jamais modifier une migration existante qui a été poussée sur un dépôt

2020-06-23 11:48 UTC, ComicScrip commented on models/apartment.model.js
> -  // constructor (appartment) {
Code mort

2020-06-23 11:48 UTC, ComicScrip commented on tests/contacts-endpoints.test.js
> +/*
code mort

2020-06-23 11:48 UTC, ComicScrip commented on controllers/apartment.controller.js
> +      const data = await Apartment.findById(req.params.id, req.params.lang);
J'avais dit dans les headers pas dans les paramètres d'url

2020-06-29 06:42 UTC, ComicScrip requested changes

2020-06-29 06:42 UTC, ComicScrip commented on models/apartment.model.js
> +    return db.query(`SELECT a.id, a.name, a.details_${lang}, a.week_price, a.month_price, a.title_${lang}, a.main_picture_url, sp.id , sp.url FROM apartment a JOIN secondary_picture sp ON a.id = sp.i
Ce code ne fait pas ce qu'il devrait faire : 
- quand l'appartement n'a pas de photo secondaire, il n'est pas trouvé. (type de jointure)
- risque d'injection SQL

2020-06-29 12:10 UTC, vbouault commented
@ComicScrip,
correction ok, normalement c'est tout bon

2020-06-30 09:27 UTC, ComicScrip approved these changes

2020-06-30 09:27 UTC, merged